Changed Link to Buttons
OData/odataorg.github.io pull request #294
Opened 2021-07-07 17:41 UTC by wachuga

2021-07-07 17:50 UTC, wachuga commented
This PR corrects the ![image](https://user-images.githubusercontent.com/41168603/124805932-d0ef4f00-df64-11eb-9139-30daf4b2d994.png)to appear as should under high contrast

Please see
https://identitydivision.visualstudio.com/OData/_workitems/edit/1366629

Note: User credentials should NOT be included in the bug.
Repro Steps:
Hit the URL https://www.odata.org/ and login with appropriate credentials to open Odata website
Tab till 'Developers' link and press enter
Tab till 'Reference Services' option and press enter
Verify all the controls in the "Odata V4" are accessible and Switch to high contrast theme and verify the issue.
Actual Result:
Tab button control is not adapting high contrast theme under Reference Services-Odata V4 blade.

Expected Result:
Tab button control should adapt high contrast theme under Reference Services-Odata V4 blade.

Note: Same issue exists throughout the application for all tab controls.

The tabs currently, (Normal mode)
![After](https://user-images.githubusercontent.com/41168603/124806014-e49ab580-df64-11eb-8f75-3af0c28ee521.JPG)

Tabs after change (Normal mode)
![image](https://user-images.githubusercontent.com/41168603/124805875-bd43e880-df64-11eb-8141-dce545463576.png)

tabs currently (High contrast)
![before](https://user-images.githubusercontent.com/41168603/124805915-cc2a9b00-df64-11eb-9465-7dd54d56e718.JPG)

Tabs after change (High contrast)
![image](https://user-images.githubusercontent.com/41168603/124805753-9685b200-df64-11eb-9e8d-10b0ca2c999d.png)

2021-07-08 06:40 UTC, habbes requested changes
@wachuga based on the screenshots. It seems your PR also changes how the tabs look in "normal" mode (i.e. when high contrast theme is not applied). Was this necessary?

Also the description states that this issues affects tabs all across the site. But your fix seems to apply to only the 3 tabs on the references page. I think it should be applied to all pages with tabs.

2021-07-08 06:46 UTC, habbes commented
@wachuga I also have another question based on the original issue description and repro:
![image](https://user-images.githubusercontent.com/8460169/124874678-acc95780-dfd0-11eb-9872-0b207acf29fa.png)

It says that tab buttons do not adapt to the high-contrast theme. But the theme settings in the above screenshots do state that hyperlinks should be yellow, which is what's currently the case. Should tab buttons not be considered as hyperlinks?

I'm comparing with how this GitHub page handles high-contrast settings. The main PR tab buttons have yellow text:
![image](https://user-images.githubusercontent.com/8460169/124875008-134e7580-dfd1-11eb-96be-ddeb3865b5f7.png)

But the tab buttons when editing a comment have white text:
![image](https://user-images.githubusercontent.com/8460169/124875118-31b47100-dfd1-11eb-8995-02bd1fa8c7f5.png)

I'm not sure what the right approach is, I think tab buttons are links and ought to be treated as links. But if you decide to keep the as buttons, then I think you should apply it to all the tabs across the site.

2021-07-08 13:54 UTC, wachuga commented
@habbes  I think the issue is that the tabs should not be links.

2021-07-09 07:09 UTC, marabooy approved these changes

2021-07-09 07:44 UTC, paulodero approved these changes

2021-07-09 08:00 UTC, habbes commented
> @habbes I think the issue is that the tabs should not be links.

I'm confused by that statement, since it seems that you kept the tabs as links. Could you explain how your changes work?

2021-07-09 08:01 UTC, habbes commented
And what about the tabs on other pages, like https://www.odata.org/getting-started/understand-odata-in-6-steps/

2021-07-12 10:59 UTC, wandeg reviewed
Has this change been tested to make sure it doesn't break existing accessibility fixes for the Narration?

2021-07-12 11:03 UTC, marabooy commented
@wandeg Could you test out some of those features. I tested navigation and a bit of naration. Ideally what I have seen is that tabs.js takes care of tab activations as well and the current narration should not be affected by the changes. We should however see if we are firing any js events that bootstrap was firing before.

2021-07-22 07:15 UTC, marabooy approved these changes

2021-07-22 07:15 UTC, marabooy commented on pages/ecosystem.html
> +<ul class="nav nav-pills nav-stacked" target="ecosystem" >
Target here is used wrongly you can use custom tags which do not change the markup and are not reserved.
e.g. data-target-tab or something of the sort.

Same for the other items in the anchors as the value for target is specified [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target) and some browsers may by default have unspecified behaviours for unknown values here. a target=something implies there is an iframe named something.

2021-07-22 07:16 UTC, marabooy requested changes
Kindly address the anchor targets and use custom attributes.

2021-07-22 07:24 UTC, marabooy commented on _includes/footer.html
> +</script>
Move to _scripts.html

2021-07-22 07:25 UTC, marabooy reviewed
Move items to scripts include.

2021-07-22 09:10 UTC, habbes commented
I've tested the changes with the narrator and keyboard navigation and found that it does not behave like the current site. 

When you tab through the pages using the Tab key, it skips the tab components on the page altogether. But when you navigate using arrows keys, then you can reach the tab items.

On the current site, you can reach the tab items using the Tab key.

I also noticed that there doesn't seem to be any UI indicator of the currently selected tab  item. But this seems to be an issue with the existing site as well. For example, looking at the image below, you can't easily tell which tab item is selected. But maybe that's beyond the scope of this PR.

![image](https://user-images.githubusercontent.com/8460169/126615380-5575d7b7-24e4-44e9-8f89-e7953f91724d.png)

2021-07-23 09:50 UTC, marabooy approved these changes

2021-07-26 06:38 UTC, habbes requested changes
I've tested with Narrator + Tabbing through page using the tab key and found the following issues:
- The sidebar links/tabs on the ecosystem page seems to be broken: clicking a link does not open the corresponding tab contents. Furthermore, when tabbing through the page, these links are skipped.
- On the Getting Started in 6 Easy Steps page, when you tab through, you eventually land on the first tab item, as expected. However when you continue to tab, it skips to the  "View Response" button without visiting the other tab items. From there it continues jumping to the next "View Response" button skipping the subsequent tab items in the process. In the original site, tabbing through the page visits all the tab items.
- On the References page, it also visits just visit the tab item when you tab through the page. But this seems to be happening in the original site as well.

2021-07-26 08:16 UTC, habbes commented
> I've tested with Narrator + Tabbing through the page using the tab key and found the following issues:
> 
> * The sidebar links/tabs on the ecosystem page seems to be broken: clicking a link does not open the corresponding tab contents. Furthermore, when tabbing through the page, these links are skipped.
> * On the Understanding OData in 6 Easy Steps page, when you tab through, you eventually land on the first tab item, as expected. However when you continue to tab, it skips to the  "View Response" button without visiting the other tab items. From there it continues jumping to the next "View Response" button skipping the subsequent tab items in the process. In the original site, tabbing through the page visits all the tab items.
> * On the References page, it also visits just visit the tab item when you tab through the page. But this seems to be happening in the original site as well.

Seems that I had not updated the branch on my local tests. My mistake. Sorry about that. Seems to work fine now.

2021-07-26 08:18 UTC, habbes approved these changes
Looks good to me.

2021-07-26 11:47 UTC, merged