Add library DynamicODataToSQL
OData/odataorg.github.io pull request #295
Opened 2021-07-15 18:11 UTC by vaibhav-goyal

Add library DynamicODataToSQL

2021-07-26 05:48 UTC, vaibhav-goyal commented
Hi @marabooy requesting your review to publish this library in Odata libraries for dotnet

2021-07-27 07:22 UTC, marabooy approved these changes

2021-07-27 07:22 UTC, marabooy commented
@vaibhav-goyal thank you for the pr. Having the team review :)

2021-07-27 12:05 UTC, KenitoInc requested changes

2021-07-27 12:05 UTC, KenitoInc commented on _libraries/DynamicODataToSQL.md
> +Library to convert OData query directly to SQL query without IQuearable or entity framework. It is useful when the data model is dynamic and hence entity framework or any other ORM with IQuerable sup
```suggestion
Library to convert OData query directly to SQL query without IQueryable or entity framework. It is useful when the data model is dynamic and hence entity framework or any other ORM with IQueryable support cannot be used.
```

2021-07-29 07:21 UTC, vaibhav-goyal commented
Thank you @marabooy and @KenitoInc for review.

2021-07-29 07:23 UTC, gathogojr approved these changes

2021-07-29 08:06 UTC, KenitoInc approved these changes

2021-07-29 08:07 UTC, merged